type Query {
	"Получаем модель User"
	authMe: User

	userById(id: ID!): User
}

type Mutation {
	"Входим под user - возвращаем JWT токен"
	authLogin(input: UserLogin!): AuthToken!

	"Выходим из авторизации - токены инвалидируются"
	authLogout: String!

	"Обновляем токены - access/refresh"
	authRefresh: AuthToken!

	"Устанавливаем полезную нагрузку, получаем новый access токен"
	authSetPayload(organization_id: ID!): AuthToken!
}

input UserLogin {
	email: String!
	phone: String
	password: String!
}

type User {
	id: ID!
	email: String
	phone: String
}

type AuthToken {
	"Токен JWT"
	access_token: String

	"Тип токена"
	token_type: String

	"Время сущестования Access токена в минутах"
	expires_in_access: String

	"Время сущестования Refresh токена в минутах"
	expires_in_refresh: String
}

"Directions for ordering a list of records."
enum SortOrder {
	"Sort records in ascending order."
	ASC

	"Sort records in descending order."
	DESC
}

"Aggregate functions when ordering by a relation without specifying a column."
enum OrderByRelationAggregateFunction {
	"Amount of items."
	COUNT
}

"Aggregate functions when ordering by a relation that may specify a column."
enum OrderByRelationWithColumnAggregateFunction {
	"Average."
	AVG

	"Minimum."
	MIN

	"Maximum."
	MAX

	"Sum."
	SUM

	"Amount of items."
	COUNT
}

"Allows ordering a list of records."
input OrderByClause {
	"The column that is used for ordering."
	column: String!

	"The direction that is used for ordering."
	order: SortOrder!
}

"Specify if you want to include or exclude trashed results from a query."
enum Trashed {
	"Only return trashed results."
	ONLY

	"Return both trashed and non-trashed results."
	WITH

	"Only return non-trashed results."
	WITHOUT
}
