name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feature/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build -t QRFrontendService .

    - name: Copy image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "QRFrontendService"
        target: "/tmp"

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker load < /tmp/QRFrontendService
          docker stop QRFrontendService || true
          docker rm QRFrontendService || true
          docker run --name QRFrontendService -d -p 80:80 QRFrontendService
