name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - feature/deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build image
      run: |
        docker build -t qr-frontend-service .
        
    - name: Save image to file
      run: |
        docker save -o qr-frontend-service.tar qr-frontend-service

    - name: Copy image to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        source: "qr-frontend-service.tar"
        target: "/tmp"

    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          docker load < /tmp/qr-frontend-service.tar
          docker stop qr-frontend-service || true
          docker rm qr-frontend-service || true
          docker run --name qr-frontend-service -d -p 80:80 qr-frontend-service
